// <copyright file="SettingsData.cs" company="PublicDomain.is">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace PublicDomain
{
    // Directives
    using System.Collections.Generic;
    using System.Drawing;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> always on top.
        /// </summary>
        /// <value><c>true</c> if always on top; otherwise, <c>false</c>.</value>
        public bool AlwaysOnTop { get; set; } = true;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> remember edits.
        /// </summary>
        /// <value><c>true</c> if remember edits; otherwise, <c>false</c>.</value>
        public bool RememberEdits { get; set; } = true;

        /// <summary>
        /// Gets or sets the constant text.
        /// </summary>
        /// <value>The constant text.</value>
        public string ConstantText { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the constant list.
        /// </summary>
        /// <value>The constant list.</value>
        public List<string> ConstantList { get; set; } = new List<string>();

        /// <summary>
        /// Gets or sets the separator text.
        /// </summary>
        /// <value>The separator text.</value>
        public string SeparatorText { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the separator list.
        /// </summary>
        /// <value>The separator list.</value>
        public List<string> SeparatorList { get; set; } = new List<string>();

        /// <summary>
        /// Gets or sets the variable value.
        /// </summary>
        /// <value>The variable value.</value>
        public decimal VariableValue { get; set; } = 1;
    }
}